# Generated by Django 3.0.14 on 2022-10-27 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import usluga_payment.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashregister_id', models.IntegerField()),
                ('kiosk_id', models.IntegerField()),
                ('receipt_id', models.IntegerField()),
                ('partner_id', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator_id', models.CharField(default=uuid.uuid4, max_length=128)),
            ],
            options={
                'get_latest_by': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(default=usluga_payment.models.random_string, max_length=128)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('received', 'RECEIVED'), ('cancelled', 'CANCELLED'), ('waiting', 'WAITING')], default='waiting', max_length=32)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usluga_payment.Customer')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usluga_payment.Operator')),
            ],
        ),
    ]
