# Generated by Django 4.1.1 on 2022-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usluga_payment', '0003_podiezd'),
    ]

    operations = [
        migrations.AddField(
            model_name='podiezd',
            name='random_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
