# Generated by Django 4.1.1 on 2022-10-06 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usluga_payment", "0006_baipinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baipinfo",
            options={"get_latest_by": ["created"]},
        ),
        migrations.AddField(
            model_name="baipinfo",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
