# Generated by Django 4.1.1 on 2022-10-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usluga_payment", "0009_alter_transaction_baip_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podiezd",
            options={"get_latest_by": ["refill_date_time"]},
        ),
    ]
