# Generated by Django 4.1.1 on 2022-10-12 14:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usluga_payment", "0010_alter_podiezd_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.IntegerField()),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cashregister_id", models.IntegerField()),
                ("kiosk_id", models.IntegerField()),
                ("receipt_id", models.IntegerField()),
                ("partner_id", models.IntegerField()),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "operator_id",
                    models.CharField(default=uuid.uuid4, max_length=128),
                ),
            ],
            options={
                "get_latest_by": ["created"],
            },
        ),
        migrations.AlterModelOptions(
            name="podiezd",
            options={},
        ),
        migrations.RemoveField(
            model_name="podiezd",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="podiezd",
            name="name",
        ),
        migrations.RemoveField(
            model_name="podiezd",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="baip_info",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="name",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BaipInfo",
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usluga_payment.customer",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usluga_payment.operator",
            ),
        ),
    ]
