# Generated by Django 4.1.1 on 2022-10-13 01:41

from django.db import migrations, models
import usluga_payment.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "usluga_payment",
            "0011_customer_operator_alter_podiezd_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_number",
            field=models.CharField(
                default=usluga_payment.models.random_string, max_length=128
            ),
        ),
    ]
