# Generated by Django 4.1.1 on 2022-10-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usluga_payment", "0012_alter_transaction_transaction_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
